blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ReviewList.as_view(), name='home'),
    path('food_recipes', views.FoodList.as_view(), name='food'),
    path('cocktail_recipes', views.CocktailList.as_view(), name='cocktail'),
    path('<slug:slug>/', views.review_detail, name='review_detail'),
    path('food_recipes/<slug:slug>/', views.food_detail, name='food_detail'),
    path(
        'cocktail_recipes/<slug:slug>/',
        views.cocktail_detail, name='cocktail_detail'),
    path(
        'food_recipes/<slug:slug>/edit_comment/<int:comment_id>',
        views.food_comment_edit, name='food_comment_edit'),
    path(
        'cocktail_recipes/<slug:slug>/edit_comment/<int:comment_id>',
        views.cocktail_comment_edit, name='cocktail_comment_edit'),
    path(
        'food_recipes/<slug:slug>/delete_comment/<int:comment_id>',
        views.food_comment_delete, name='food_comment_delete'),
    path(
        'cocktail_recipes/<slug:slug>/delete_comment/<int:comment_id>',
        views.cocktail_comment_delete, name='cocktail_comment_delete'),
]

gabbygourmand/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("about/", include("about.urls"), name="about-urls"),
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("", include("blog.urls"), name="blog-urls"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))
RATING = (
    (5, "Excellent - 5 Stars"), (4, "Good - 4 Stars"), (3, "Ok - 3 Stars"),
    (2, "Could Be Better - 2 Stars"),
    (1, "Poor - 1 Star"), (0, "Really Bad - 0 Stars"))
PRICE = ((0, "Low"), (1, "Medium"), (2, "High"))
TYPE = ((0, "Food"), (1, "Cocktail"))


class Review(models.Model):
    """
    Stores a single restaurant review related to :model:`auth.User`.
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_reviews"
    )
    featured_image_1 = CloudinaryField('image', default='placeholder')
    featured_image_2 = CloudinaryField('image', default='placeholder')
    featured_image_3 = CloudinaryField('image', default='placeholder')
    restaurant = models.CharField(max_length=200)
    content = models.TextField()
    location = models.CharField(max_length=200)
    visited_on = models.DateTimeField()
    rating = models.IntegerField(choices=RATING, default=5)
    price = models.IntegerField(choices=PRICE, default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.title} | written by {self.author}"


class Recipe(models.Model):
    """
    Stores a single recipe related to :model:`auth.User`.
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_recipes"
    )
    featured_image_1 = CloudinaryField('image', default='placeholder')
    featured_image_2 = CloudinaryField('image', default='placeholder')
    featured_image_3 = CloudinaryField('image', default='placeholder')
    ingredients = models.TextField()
    instructions = models.TextField()
    type = models.IntegerField(choices=TYPE, default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.title} | written by {self.author}"


class Comment(models.Model):
    """
    Stores a single comment related to :model:`auth.User`
    and :model:`blog.recipe`.
    """
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="commenter")
    body = models.TextField()
    approved = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"{self.body} by {self.author}"

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    """
    Form for users to comment on a post 
    """
    class Meta:
        model = Comment
        fields = ('body',)

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Review, Recipe, Comment
from .forms import CommentForm


class ReviewList(generic.ListView):
    queryset = Review.objects.filter(status=1)
    template_name = "blog/index.html"
    paginate_by = 6


class FoodList(generic.ListView):
    queryset = Recipe.objects.filter(status=1, type=0)
    template_name = "blog/food.html"
    paginate_by = 6


class CocktailList(generic.ListView):
    queryset = Recipe.objects.filter(status=1, type=1)
    template_name = "blog/cocktail.html"
    paginate_by = 6


def review_detail(request, slug):
    """
    Displays an individual instance of :model:`blog.Review`.
    **Context**
    ``review``
        An instance of :model:`blog.Review`.
    **Template:**
    :template:`blog/review_detail.html`
    """
    queryset = Review.objects.filter(status=1)
    review = get_object_or_404(queryset, slug=slug)

    return render(
        request,
        "blog/review_detail.html",
        {"review": review},
    )


def food_detail(request, slug):
    """
    Displays an individual instance of :model:`blog.Recipe`.
    **Context**
    ``recipe``
        An instance of :model:`blog.Recipe`.
    ``comments``
        All approved comments related to the recipe.
    ``comment_count``
        A count of approved comments related to the recipe.
    ``comment_form``
        An instance of :form:`blog.CommentForm`.
    **Template:**
    :template:`blog/food_detail.html`
    """
    queryset = Recipe.objects.filter(status=1, type=0)
    recipe = get_object_or_404(queryset, slug=slug)
    comments = recipe.comments.all().order_by("-created_on")
    comment_count = recipe.comments.filter(approved=True).count()

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.recipe = recipe
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Comment submitted and awaiting approval'
            )

    comment_form = CommentForm()

    return render(
        request,
        "blog/food_detail.html",
        {"recipe": recipe,
            "comments": comments,
            "comment_count": comment_count,
            "comment_form": comment_form, },
    )


def cocktail_detail(request, slug):
    """
    Displays an individual instance of :model:`blog.Recipe`.
    **Context**
    ``recipe``
        An instance of :model:`blog.Recipe`.
    ``comments``
        All approved comments related to the recipe.
    ``comment_count``
        A count of approved comments related to the recipe.
    ``comment_form``
        An instance of :form:`blog.CommentForm`.
    **Template:**
    :template:`blog/cocktail_detail.html`
    """
    queryset = Recipe.objects.filter(status=1, type=1)
    recipe = get_object_or_404(queryset, slug=slug)
    comments = recipe.comments.all().order_by("-created_on")
    comment_count = recipe.comments.filter(approved=True).count()

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.recipe = recipe
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Comment submitted and awaiting approval'
            )

    comment_form = CommentForm()

    return render(
        request,
        "blog/cocktail_detail.html",
        {"recipe": recipe,
            "comments": comments,
            "comment_count": comment_count,
            "comment_form": comment_form, },
    )


def food_comment_edit(request, slug, comment_id):
    """
    Displays an individual comment for edit.
    **Context**
    ``recipe``
        An instance of :model:`blog.Recipe`.
    ``comment``
        A single comment related to the recipe.
    ``comment_form``
        An instance of :form:`blog.CommentForm`.
    """
    if request.method == "POST":

        queryset = Recipe.objects.filter(status=1, type=0)
        recipe = get_object_or_404(queryset, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.recipe = recipe
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
        else:
            messages.add_message(
                request, messages.ERROR, 'Error updating comment!')

    return HttpResponseRedirect(reverse('food_detail', args=[slug]))


def cocktail_comment_edit(request, slug, comment_id):
    """
    Displays an individual comment for edit.
    **Context**
    ``recipe``
        An instance of :model:`blog.Recipe`.
    ``comment``
        A single comment related to the recipe.
    ``comment_form``
        An instance of :form:`blog.CommentForm`.
    """
    if request.method == "POST":

        queryset = Recipe.objects.filter(status=1, type=1)
        recipe = get_object_or_404(queryset, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.recipe = recipe
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
        else:
            messages.add_message(
                request, messages.ERROR, 'Error updating comment!')

    return HttpResponseRedirect(reverse('cocktail_detail', args=[slug]))


def food_comment_delete(request, slug, comment_id):
    """
    Delete an individual comment.
    **Context**
    ``recipe``
        An instance of :model:`blog.Recipe`.
    ``comment``
        A single comment related to the recipe.
    """
    queryset = Recipe.objects.filter(status=1, type=0)
    recipe = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(
            request, messages.ERROR, 'You can only delete your own comments!')

    return HttpResponseRedirect(reverse('food_detail', args=[slug]))


def cocktail_comment_delete(request, slug, comment_id):
    """
    Delete an individual comment.
    **Context**
    ``recipe``
        An instance of :model:`blog.Recipe`.
    ``comment``
        A single comment related to the recipe.
    """
    queryset = Recipe.objects.filter(status=1, type=1)
    recipe = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(
            request, messages.ERROR, 'You can only delete your own comments!')

    return HttpResponseRedirect(reverse('cocktail_detail', args=[slug]))

blog/templates/blog/cocktail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- cocktail.html content starts -->
<div class="container-fluid">
    <div class="row">
        <!-- Blog Entries -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for recipe in recipe_list %}
                <div class="col-md-4">
                    <div class="card mb-4 bg-transparent">
                        <div class="card-body">
                            <a href="{% url 'cocktail_detail' recipe.slug %}" class="cocktail-link">
                                <h1 class="card-title">{{ recipe.title }}</h1>
                            </a>
                            <hr>
                            <div class="image-container">
                                {% if "placeholder" in review.featured_image.url %}
                                <a href="{% url 'cocktail_detail' recipe.slug %}">
                                    <img class="card-img-top" src="{% static 'images/default.jpg' %}"
                                        alt="placeholder image"></a>
                                {% else %}
                                <a href="{% url 'cocktail_detail' recipe.slug %}">
                                    <img class="card-img-top" src=" {{ recipe.featured_image_1.url }}"
                                        alt="{{ review.title }}"></a>
                                {% endif %}
                                <br>
                                <br>
                                <div class="image-flash">
                                    <p class="author">Author: {{ recipe.author }}</p>
                                </div>
                            </div>
                            <p class="card-text fst-italic">{{ recipe.created_on}}
                            </p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREVIOUS</a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li>
                <a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
<!-- cocktail.html content ends -->
{% endblock %}

blog/templates/blog/cocktail_detail.html
{% extends 'base.html' %} {% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card mb-3 py-3 px-3 bg-transparent">
        <!-- Recipe Title & Author-->
        <h1 class="recipe-title">{{ recipe.title }}</h1>
        <p class="recipe-subtitle">{{ recipe.author }} | {{ recipe.created_on }}</p>
      </div>
    </div>
  </div>
  <div class="row">
    <!-- Recipe Images -->
    <div class="col-12 col-sm-6 col-md-4">
      <div class="card mb-3 bg-transparent">
        {% if "placeholder" in review.featured_image.url %}
        <img src="{% static 'images/default.jpg' %}" alt="placeholder image">
        {% else %}
        <img src=" {{ recipe.featured_image_1.url }} " alt="{{ recipe.title }}">
        {% endif %}
      </div>
    </div>
    <div class="col-12 col-sm-6 col-md-4">
      <div class="card mb-3 bg-transparent">
        {% if "placeholder" in review.featured_image.url %}
        <img src="{% static 'images/default.jpg' %}" alt="placeholder image">
        {% else %}
        <img src=" {{ recipe.featured_image_2.url }} " alt="{{ recipe.title }}">
        {% endif %}
      </div>
    </div>
    <div class="col-12 col-sm-6 col-md-4 d-none d-md-block">
      <div class="card mb-3 bg-transparent">
        {% if "placeholder" in review.featured_image.url %}
        <img src="{% static 'images/default.jpg' %}" alt="placeholder image">
        {% else %}
        <img src=" {{ recipe.featured_image_3.url }} " alt="{{ recipe.title }}">
        {% endif %}
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="card mb-3 py-3 px-3 bg-transparent">
        <!-- Recipe Ingredients -->
        <article class="card-text">
          <h2>Ingredients</h2>
          {{ recipe.ingredients | safe }}
        </article>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="card mb-3 py-3 px-3 bg-transparent">
        <!-- Recipe Method -->
        <article class="card-text">
          <h3>Method</h3>
          {{ recipe.instructions | safe }}
        </article>
      </div>
    </div>
  </div>
  <!-- Display Count of Comments -->
  <div class="row">
    <div class="col-12">
      <strong class="text-secondary">
        <i class="far fa-comments"></i> {{ comment_count }}
      </strong>
    </div>
    <div class="col-12">
      <hr>
    </div>
  </div>
  <!-- Display Comments -->
  <div class="row">
    <div class="col-md-8 card mb-3 mt-3 py-3 px-4 bg-transparent">
      <h4>Comments:</h4>
      <div class="card-body">
        <!-- for loop to iterate through each comment in comments -->
        {% for comment in comments %}
        <div class="p-2 comments
        {% if not comment.approved and comment.author == user %}
        fw-light {% elif not comment.approved %} d-none {% endif %}">
          <p class="font-weight-bold">
            {{ comment.author }}
            <span class="font-weight-normal">
              {{ comment.created_on }}
            </span> wrote:
          </p>
          <div id="comment{{ comment.id }}">
            {{ comment.body | linebreaks }}
          </div>
          {% if not comment.approved and comment.author == user %}
          <p class="approval">
            This comment is awaiting approval
          </p>
          {% endif %}
          {% if user.is_authenticated and comment.author == user %}
          <button class="btn btn-edit btn-secondary" data-comment_id="{{ comment.id }}">Edit</button>
          <button class="btn btn-delete btn-danger" data-comment_id="{{ comment.id }}">Delete</button>
          {% endif %}
        </div>
        <!-- for loop ends here -->
        {% endfor %}
      </div>
    </div>
    <!-- Create New Comments -->
    <div class="col-md-4 card mb-3 mt-3 bg-transparent">
      <div class="card-body">
        {% if user.is_authenticated %}
        <h5>Leave a comment:</h5>
        <p>Posting as: {{ user.username }}</p>
        <form id="commentForm" method="post" style="margin-top: 1.3em;">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button id="submitButton" type="submit" class="btn btn-secondary">Submit</button>
        </form>
        {% else %}
        <p><a href="{{ login_url }}">Log In</a> to leave a comment</p>
        {% endif %}
      </div>
    </div>
  </div>
</div>
<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment?
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button id="closeButton" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block extras %}
<script src="{% static 'js/comments.js' %}"></script>
{% endblock %}

blog/templates/blog/food.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- food.html content starts -->
<div class="container-fluid">
    <div class="row">
        <!-- Blog Entries -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for recipe in recipe_list %}
                <div class="col-md-4">
                    <div class="card mb-4 bg-transparent">
                        <div class="card-body">
                            <a href="{% url 'food_detail' recipe.slug %}" class="food-link">
                                <h1 class="card-title">{{ recipe.title }}</h1>
                            </a>
                            <hr>
                            <div class="image-container">
                                {% if "placeholder" in review.featured_image.url %}
                                <a href="{% url 'food_detail' recipe.slug %}">
                                    <img class="card-img-top" src="{% static 'images/default.jpg' %}"
                                        alt="placeholder image"></a>
                                {% else %}
                                <a href="{% url 'food_detail' recipe.slug %}">
                                    <img class="card-img-top" src=" {{ recipe.featured_image_1.url }}"
                                        alt="{{ review.title }}"></a>
                                {% endif %}
                                <br>
                                <br>
                                <div class="image-flash">
                                    <p class="author">Author: {{ recipe.author }}</p>
                                </div>
                            </div>
                            <p class="card-text fst-italic">{{ recipe.created_on}}
                            </p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREVIOUS</a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li>
                <a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
<!-- food.html content ends -->
{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- index.html content starts -->
<div class="container-fluid">
    <div class="row">
        <!-- Blog Entries -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for review in review_list %}
                <div class="col-md-4">
                    <div class="card mb-4 bg-transparent">
                        <div class="card-body">
                            <a href="{% url 'review_detail' review.slug %}" class="review-link">
                                <h1 class="card-title">{{ review.title }}</h1>
                            </a>
                            <hr>
                            <div class="image-container">
                                {% if "placeholder" in review.featured_image.url %}
                                <a href="{% url 'review_detail' review.slug %}">
                                    <img class="card-img-top" src="{% static 'images/default.jpg' %}"
                                        alt="placeholder image"></a>
                                {% else %}
                                <a href="{% url 'review_detail' review.slug %}">
                                    <img class="card-img-top" src=" {{ review.featured_image_1.url }}"
                                        alt="{{ review.title }}"></a>
                                {% endif %}
                                <br>
                                <br>
                                <div class="image-flash">
                                    <p class="restaurant">Restaurant: {{ review.restaurant }}</p>
                                    <p class="location">Location: {{ review.location }}</p>
                                    <p class="author">Author: {{ review.author }}</p>
                                </div>
                            </div>
                            <p class="card-text fst-italic">{{ review.created_on}}
                            </p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREVIOUS</a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li>
                <a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
<!-- index.html content ends -->
{% endblock %}

blog/templates/blog/review_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card mb-3 py-3 px-3 bg-transparent">
                <!-- Review Title & Author-->
                <h1 class="review-title">{{ review.title }}</h1>
                <p class="review-subtitle">{{ review.author }} | {{ review.created_on }}</p>
                <hr>
                <br>
                <!-- Review Detail -->
                <p>Visited on: {{ review.visited_on }}</p>
                <p>Rating: {{ review.get_rating_display }}</p>
                <p>Price Range: {{ review.get_price_display }}</p>
            </div>
        </div>
    </div>
    <div class="row">
        <!-- Review Images -->
        <div class="col-12 col-sm-6 col-md-4">
            <div class="card mb-3 bg-transparent">
                {% if "placeholder" in review.featured_image.url %}
                <img src="{% static 'images/default.jpg' %}" alt="placeholder image">
                {% else %}
                <img src=" {{ review.featured_image_1.url }} " alt="{{ review.title }}">
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-4">
            <div class="card mb-3 bg-transparent">
                {% if "placeholder" in review.featured_image.url %}
                <img src="{% static 'images/default.jpg' %}" alt="placeholder image">
                {% else %}
                <img src=" {{ review.featured_image_2.url }} " alt="{{ review.title }}">
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-4 d-none d-md-block">
            <div class="card mb-3 bg-transparent">
                {% if "placeholder" in review.featured_image.url %}
                <img src="{% static 'images/default.jpg' %}" alt="placeholder image">
                {% else %}
                <img src=" {{ review.featured_image_3.url }} " alt="{{ review.title }}">
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card mb-3 py-3 px-3 bg-transparent">
                <!-- Review Content -->
                <article class="card-text">
                    <h2>Review</h2>
                    {{ review.content | safe }}
                </article>
            </div>
        </div>
    </div>
</div>

{% endblock content %}